// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("UpstreamAnalysisWorkflow")>]
[<assembly: AssemblyProductAttribute("UpstreamAnalysisWorkflow")>]
[<assembly: AssemblyDescriptionAttribute("A project to simplify the process of preparing a set of genes for upstream analysis. Uses the Bi-directional best hit method to identify homologous genes and finds their upstream regions. Makes use of the Experimental-dotnetbioGenBankProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "UpstreamAnalysisWorkflow"
    let [<Literal>] AssemblyProduct = "UpstreamAnalysisWorkflow"
    let [<Literal>] AssemblyDescription = "A project to simplify the process of preparing a set of genes for upstream analysis. Uses the Bi-directional best hit method to identify homologous genes and finds their upstream regions. Makes use of the Experimental-dotnetbioGenBankProvider."
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
